import {SignalBus} from './runtime/signal-bus.js';
import {RuntimeScheduler} from './runtime/scheduler.js';
import {SourceEngine} from './runtime/source-engine.js';
import {AnalysisEngine} from './runtime/analysis-engine.js';
import {CVEngine} from './runtime/cv-engine.js';
import {EffectRegistry} from './runtime/effect-registry.js';
import {EffectComposer} from './runtime/composer.js';
import {feedbackFactory,displacementFactory,reactionFactory} from './effects/gpu-effects.js';
import {slitScanFactory,flowParticlesFactory,pixelSortFactory,poseDepthFactory,poseMeshFactory,hdBeadsFactory,beadsFactory,ringsFactory,asciiFactory} from './effects/cpu-effects.js';
import {poseParticleFactory} from './effects/pose-particles.js';
const bus=new SignalBus({style:document.documentElement.dataset.style||'prism'}),scheduler=new RuntimeScheduler(bus),video=document.getElementById('camera'),preview=document.getElementById('sourcePreview'),source=new SourceEngine({bus,video,preview}),analysis=new AnalysisEngine({bus,source}),cv=new CVEngine({bus,source}),registry=new EffectRegistry({scheduler,bus,source,analysis,cv}),compositeCanvas=document.getElementById('compositeStage'),composer=new EffectComposer({canvas:compositeCanvas,bus,source,analysis,cv});
const defs=[
{id:'feedback',engine:'webgl2',fps:40,offscreenFps:5,stateful:true,inputs:['frame','history','motion','mask'],factory:feedbackFactory},
{id:'displacement',engine:'webgl2',fps:40,inputs:['frame','lucas-kanade-flow','mask'],factory:displacementFactory},
{id:'slitscan',engine:'canvas2d',fps:24,offscreenFps:4,stateful:true,inputs:['frame-history'],factory:slitScanFactory},
{id:'pointcloud',engine:'canvas2d',fps:24,inputs:['frame','pose-mask','pose-landmarks'],factory:poseDepthFactory},
{id:'flow',engine:'canvas2d',fps:40,offscreenFps:4,stateful:true,inputs:['lucas-kanade-flow'],factory:flowParticlesFactory},
{id:'triangulation',engine:'canvas2d',fps:20,inputs:['pose-landmarks'],factory:poseMeshFactory},
{id:'pixelsort',engine:'canvas2d',fps:18,inputs:['frame','motion'],factory:pixelSortFactory},
{id:'reaction',engine:'webgl2',fps:30,offscreenFps:5,stateful:true,inputs:['frame','mask','motion'],factory:reactionFactory},
{id:'hdbeads',engine:'canvas2d',fps:20,inputs:['frame','mask'],factory:hdBeadsFactory},
{id:'beads',engine:'canvas2d',fps:18,inputs:['frame','mask'],factory:beadsFactory},
{id:'rings',engine:'canvas2d',fps:30,inputs:['motion-center','flow-average'],factory:ringsFactory},
{id:'ascii',engine:'canvas2d',fps:16,inputs:['frame','luma'],factory:asciiFactory},
{id:'pose-particles',canvasId:'threeStage',engine:'webgl2',fps:45,offscreenFps:8,stateful:true,inputs:['pose-landmarks','mask','motion'],factory:poseParticleFactory}];
for(const d of defs)registry.register(d);
scheduler.register({id:'source',fps:60,hiddenFps:5,callback:t=>source.tick(t)});scheduler.register({id:'analysis',fps:28,hiddenFps:3,callback:t=>analysis.tick(t)});scheduler.register({id:'cv',fps:10,hiddenFps:1,callback:t=>cv.tick(t)});scheduler.register({id:'composer',fps:45,offscreenFps:8,element:compositeCanvas,callback:t=>composer.render(t)});scheduler.register({id:'telemetry',fps:12,offscreenFps:4,element:document.querySelector('.telemetry-band'),callback:t=>drawTelemetry(t)});
const cameraButton=document.getElementById('cameraButton'),syntheticButton=document.getElementById('syntheticButton'),wireframeButton=document.getElementById('wireframeButton'),burstButton=document.getElementById('burstButton'),intensity=document.getElementById('intensity'),status=document.getElementById('status');let poseOverlay=true,burstTimer=0;
cameraButton?.addEventListener('click',async()=>{try{status.textContent='正在请求摄像头…';await source.useCamera();status.textContent='摄像头已连接；正在加载 Pose / Mask CV。';cv.init();}catch(error){console.warn(error);source.useSynthetic();status.textContent='摄像头不可用，已回退合成源。';}});syntheticButton?.addEventListener('click',()=>{source.useSynthetic();status.textContent='使用合成源；Optical Flow 与 GPU 效果继续运行。';});wireframeButton?.addEventListener('click',()=>{poseOverlay=!poseOverlay;registry.setEnabled('pose-particles',poseOverlay);wireframeButton.classList.toggle('is-active',poseOverlay);wireframeButton.setAttribute('aria-pressed',String(poseOverlay));});burstButton?.addEventListener('click',()=>{clearTimeout(burstTimer);const previous=Number(intensity?.value||1);bus.publish({intensity:1.8,burst:1});if(intensity)intensity.value='1.8';burstButton.classList.add('is-active');burstTimer=setTimeout(()=>{bus.publish({intensity:previous,burst:0});if(intensity)intensity.value=String(previous);burstButton.classList.remove('is-active');},1800);});intensity?.addEventListener('input',()=>bus.publish({intensity:Number(intensity.value)}));
for(const button of document.querySelectorAll('.style-mode'))button.addEventListener('click',()=>{const style=button.dataset.style||'prism';document.documentElement.dataset.style=style;source.setStyle(style);bus.publish({style});for(const other of document.querySelectorAll('.style-mode')){const active=other===button;other.classList.toggle('is-active',active);other.setAttribute('aria-pressed',String(active));}});source.setStyle(bus.state.style);bus.publish({intensity:Number(intensity?.value||1)});
const signalMap=document.getElementById('signalMap'),signalCtx=signalMap?.getContext('2d');function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value;}function drawTelemetry(){const s=bus.snapshot();if(signalCtx){const w=signalMap.width,h=signalMap.height;signalCtx.fillStyle='#030509';signalCtx.fillRect(0,0,w,h);signalCtx.globalCompositeOperation='lighter';for(let gy=0;gy<analysis.gridH;gy++)for(let gx=0;gx<analysis.gridW;gx++){const i=(gy*analysis.gridW+gx)*2,vx=analysis.flow[i],vy=analysis.flow[i+1],x=(gx+.5)/analysis.gridW*w,y=(gy+.5)/analysis.gridH*h,mag=Math.hypot(vx,vy);if(mag<.03)continue;signalCtx.strokeStyle=`hsla(${190+Math.min(140,mag*25)},100%,70%,${Math.min(.9,.15+mag*.18)})`;signalCtx.lineWidth=.7+Math.min(2,mag*.2);signalCtx.beginPath();signalCtx.moveTo(x,y);signalCtx.lineTo(x+vx*6,y+vy*6);signalCtx.stroke();}signalCtx.fillStyle='rgba(255,255,255,.9)';signalCtx.fillRect(s.motionX*w-2,s.motionY*h-2,4,4);signalCtx.globalCompositeOperation='source-over';}setText('statFrame',String(s.frame||0).padStart(4,'0'));setText('statFps',(s.analysisFps||0).toFixed(1));setText('statLuma',(s.luma||0).toFixed(3));setText('statMotion',(s.motion||0).toFixed(3));setText('statCenter',`${(s.motionX||.5).toFixed(2)}×${(s.motionY||.5).toFixed(2)}`);const stats=scheduler.stats(),total=Object.values(stats).reduce((sum,item)=>sum+item.costMs,0);setText('statRuntime',`${total.toFixed(1)}ms`);setText('statTriangles',s.poseReady?`${s.poseCount}P`:'--');setText('signalState',`${String(s.source).toUpperCase()} / REAL LK FLOW / CV ${String(s.cvStatus).toUpperCase()}`);setText('stageInput',String(s.source).toUpperCase());setText('stageDepth',Math.hypot(s.flowX||0,s.flowY||0).toFixed(2));setText('stageNodes',s.poseReady?`${s.poseCount} POSE`:'FLOW');setText('stagePhase',String(s.cvStatus||'idle').toUpperCase().slice(0,8));setText('stageState',s.poseReady?'MEDIAPIPE POSE + MASK → GPU PARTICLE FIELD':s.cvStatus==='loading'?'LOADING POSE / MASK MODEL…':'LUCAS–KANADE FLOW + GPU COMPOSER / CV OPTIONAL');setText('readout-flow',`LK ${Math.hypot(s.flowX||0,s.flowY||0).toFixed(2)}`);setText('readout-pointcloud',s.poseReady?`POSE ${s.poseCount}`:'MASK --');setText('readout-triangulation',s.poseReady?'LANDMARKS':'WAIT CV');setText('readout-reaction',`GPU ${(s.motion||0).toFixed(2)}`);}
function savePreset(name='default'){const preset={style:bus.state.style,intensity:bus.state.intensity,chain:[...composer.chain],effects:registry.manifest()};localStorage.setItem(`td-effect:preset:${name}`,JSON.stringify(preset));return preset;}function loadPreset(name='default'){const raw=localStorage.getItem(`td-effect:preset:${name}`);if(!raw)return null;const preset=JSON.parse(raw);if(preset.style){document.documentElement.dataset.style=preset.style;source.setStyle(preset.style);bus.publish({style:preset.style});}if(Number.isFinite(preset.intensity)){bus.publish({intensity:preset.intensity});if(intensity)intensity.value=String(preset.intensity);}if(Array.isArray(preset.chain))composer.setChain(preset.chain);return preset;}
let recorder=null,recordChunks=[];function startRecording(){if(recorder?.state==='recording')return recorder;if(!compositeCanvas.captureStream||!window.MediaRecorder)throw new Error('MediaRecorder/captureStream not supported');const stream=compositeCanvas.captureStream(30);recordChunks=[];recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'});recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data);};recorder.start(500);bus.publish({recording:true});return recorder;}function stopRecording(){return new Promise(resolve=>{if(!recorder||recorder.state!=='recording'){resolve(null);return;}recorder.onstop=()=>{const blob=new Blob(recordChunks,{type:recorder.mimeType||'video/webm'});bus.publish({recording:false});resolve(blob);};recorder.stop();});}
window.TDEngine={version:'0.3.0',bus,scheduler,source,analysis,cv,registry,composer,setChain:chain=>composer.setChain(chain),savePreset,loadPreset,startRecording,stopRecording,manifest:()=>registry.manifest()};scheduler.start();window.addEventListener('beforeunload',()=>{scheduler.stop();registry.dispose();composer.dispose();cv.dispose();source.stopCamera();});
