const VERTEX=`#version 300 es
precision highp float;
const vec2 POS[3]=vec2[3](vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));
out vec2 vUv;
void main(){vec2 p=POS[gl_VertexID];vUv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const PASSES={
passthrough:`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uSource;void main(){outColor=texture(uSource,vUv);}`,
flowWarp:`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uSource;uniform sampler2D uFlow;uniform sampler2D uMask;uniform float uTime;uniform float uIntensity;uniform float uMotion;void main(){vec3 f=texture(uFlow,vUv).rgb;vec2 flow=(f.rg-.5)*vec2(.095,-.095)*(.35+uIntensity)*(.35+uMotion*2.2);float mask=texture(uMask,vUv).r;vec2 radial=normalize(vUv-.5+.0001)*sin(length(vUv-.5)*54.-uTime*3.2)*.003*uMotion;vec2 uv=vUv-flow*(.65+mask*.9)+radial;vec3 c;c.r=texture(uSource,uv+flow*.28).r;c.g=texture(uSource,uv).g;c.b=texture(uSource,uv-flow*.28).b;outColor=vec4(c,1.);}`,
feedback:`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uSource;uniform sampler2D uHistory;uniform sampler2D uMask;uniform float uTime;uniform float uIntensity;uniform float uMotion;uniform vec2 uCenter;void main(){vec2 pivot=mix(vec2(.5),uCenter,.45);vec2 p=vUv-pivot;float a=.006+sin(uTime*.7)*.003;mat2 r=mat2(cos(a),-sin(a),sin(a),cos(a));vec2 huv=pivot+r*p*(1.008+uIntensity*.004+uMotion*.025);vec3 now=texture(uSource,vUv).rgb;vec3 prev=texture(uHistory,huv).rgb;float mask=texture(uMask,vUv).r;float keep=clamp(.79+uIntensity*.055+mask*.05,.72,.93);vec3 c=mix(now,prev*vec3(.99,.985,1.015),keep);c+=now*(.16+uMotion*.42);outColor=vec4(c,1.);}`,
maskGlow:`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uSource;uniform sampler2D uMask;uniform float uTime;uniform float uMotion;void main(){vec2 px=vec2(1./640.,1./360.);float m=texture(uMask,vUv).r;float blur=0.;for(int y=-2;y<=2;y++)for(int x=-2;x<=2;x++)blur+=texture(uMask,vUv+vec2(float(x),float(y))*px*2.).r;blur/=25.;float edge=max(0.,blur-m*.72);vec3 c=texture(uSource,vUv).rgb;vec3 glow=.5+.5*cos(vec3(0.,2.1,4.2)+uTime*.55+vUv.xyx*5.);c+=glow*edge*(.55+uMotion*1.8);c*=.92+m*.14;outColor=vec4(c,1.);}`,
chromatic:`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uSource;uniform float uIntensity;uniform float uMotion;uniform vec2 uCenter;void main(){vec2 dir=normalize(vUv-uCenter+.0001);float d=(.0015+uMotion*.009)*uIntensity;float r=texture(uSource,vUv+dir*d).r;float g=texture(uSource,vUv).g;float b=texture(uSource,vUv-dir*d).b;outColor=vec4(r,g,b,1.);}`};
function shader(gl,type,source){const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh;}
function program(gl,fragment){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,VERTEX));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
function texture(gl,width=2,height=2){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);return t;}
export class GLPipeline{
constructor(canvas,{alpha=false}={}){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error('WebGL2 is required');this.programs=new Map(Object.entries(PASSES).map(([name,frag])=>[name,program(this.gl,frag)]));this.sourceTex=texture(this.gl);this.flowTex=texture(this.gl);this.maskTex=texture(this.gl);this.historyTex=texture(this.gl,canvas.width,canvas.height);this.ping=texture(this.gl,canvas.width,canvas.height);this.pong=texture(this.gl,canvas.width,canvas.height);this.fbo=this.gl.createFramebuffer();this.vao=this.gl.createVertexArray();this.gl.bindVertexArray(this.vao);this.historyValid=false;}
_upload(tex,canvas){const gl=this.gl;gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,canvas);}
render({source,flow,mask,chain=['passthrough'],signal,time}){const gl=this.gl;this._upload(this.sourceTex,source);if(flow)this._upload(this.flowTex,flow);if(mask)this._upload(this.maskTex,mask);if(!this.historyValid){gl.bindTexture(gl.TEXTURE_2D,this.historyTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,this.canvas.width,this.canvas.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);this.historyValid=true;}let input=this.sourceTex;for(let i=0;i<chain.length;i++){const p=this.programs.get(chain[i])||this.programs.get('passthrough'),last=i===chain.length-1,output=i%2===0?this.ping:this.pong;if(last)gl.bindFramebuffer(gl.FRAMEBUFFER,null);else{gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,output,0);}gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.useProgram(p);this._bind(p,'uSource',input,0);this._bind(p,'uFlow',this.flowTex,1);this._bind(p,'uMask',this.maskTex,2);this._bind(p,'uHistory',this.historyTex,3);this._f(p,'uTime',time*.001);this._f(p,'uIntensity',signal.intensity||1);this._f(p,'uMotion',signal.motion||0);this._v2(p,'uCenter',signal.motionX||.5,1-(signal.motionY||.5));gl.drawArrays(gl.TRIANGLES,0,3);input=output;}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindTexture(gl.TEXTURE_2D,this.historyTex);gl.copyTexImage2D(gl.TEXTURE_2D,0,gl.RGBA,0,0,this.canvas.width,this.canvas.height,0);}
_bind(p,name,tex,unit){const gl=this.gl,loc=gl.getUniformLocation(p,name);if(loc===null)return;gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(loc,unit);}
_f(p,name,v){const loc=this.gl.getUniformLocation(p,name);if(loc!==null)this.gl.uniform1f(loc,v);}
_v2(p,name,x,y){const loc=this.gl.getUniformLocation(p,name);if(loc!==null)this.gl.uniform2f(loc,x,y);}
dispose(){const gl=this.gl;for(const p of this.programs.values())gl.deleteProgram(p);for(const t of[this.sourceTex,this.flowTex,this.maskTex,this.historyTex,this.ping,this.pong])gl.deleteTexture(t);gl.deleteFramebuffer(this.fbo);gl.deleteVertexArray(this.vao);}}
