const TAU=Math.PI*2;
const POSE_CONNECTIONS=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28],[27,29],[29,31],[28,30],[30,32]];
const ctx2d=c=>c.getContext('2d',{alpha:false});
export class SlitScanEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);this.history=[];this.max=48;this.temp=document.createElement('canvas');this.temp.width=160;this.temp.height=120;this.tctx=this.temp.getContext('2d');}render({source,signal,time}){this.tctx.drawImage(source,0,0,this.temp.width,this.temp.height);const frame=this.tctx.getImageData(0,0,this.temp.width,this.temp.height);this.history.push(frame);if(this.history.length>this.max)this.history.shift();const out=this.tctx.createImageData(this.temp.width,this.temp.height),d=out.data;for(let y=0;y<this.temp.height;y++){const wave=(Math.sin(y*.085+time*.0015)+1)*.5,age=Math.min(this.history.length-1,Math.floor(wave*(this.history.length-1)*(.6+signal.intensity*.45))),src=this.history[Math.max(0,this.history.length-1-age)]?.data||frame.data,row=y*this.temp.width*4;d.set(src.subarray(row,row+this.temp.width*4),row);}this.tctx.putImageData(out,0,0);this.ctx.imageSmoothingEnabled=false;this.ctx.drawImage(this.temp,0,0,this.canvas.width,this.canvas.height);}}
export class OpticalFlowParticlesEffect{constructor(canvas,analysis,count=1800){this.canvas=canvas;this.ctx=ctx2d(canvas);this.analysis=analysis;this.particles=Array.from({length:count},()=>({x:Math.random(),y:Math.random(),age:Math.random()*100,h:Math.random()}));}render({source,signal,time,dt}){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.globalCompositeOperation='source-over';c.fillStyle='rgba(2,5,10,.13)';c.fillRect(0,0,w,h);c.globalCompositeOperation='lighter';for(const p of this.particles){const[vx,vy]=this.analysis.sampleFlow(p.x,p.y),ox=p.x,oy=p.y,speed=Math.hypot(vx,vy),gain=(.012+signal.intensity*.006)*(1+signal.motion*2.5);p.x+=vx*gain+Math.sin(time*.001+p.h*9)*.0002;p.y+=vy*gain+Math.cos(time*.0013+p.h*11)*.0002;p.age+=dt*60;if(p.x<0||p.x>1||p.y<0||p.y>1||p.age>180){p.x=Math.random();p.y=Math.random();p.age=0;p.h=Math.random();continue;}const hue=(190+p.h*150+speed*30)%360,alpha=Math.min(.65,.05+speed*.12+signal.motion*.2);c.strokeStyle=`hsla(${hue},95%,68%,${alpha})`;c.lineWidth=.45+Math.min(2,speed*.45);c.beginPath();c.moveTo(ox*w,oy*h);c.lineTo(p.x*w,p.y*h);c.stroke();if(speed>.45){c.fillStyle=`hsla(${(hue+45)%360},100%,82%,${alpha})`;c.fillRect(p.x*w-1,p.y*h-1,2,2);}}c.globalCompositeOperation='source-over';if(signal.motion<.01){c.globalAlpha=.08;c.drawImage(source,0,0,w,h);c.globalAlpha=1;}}}
export class PixelSortEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);this.temp=document.createElement('canvas');this.temp.width=128;this.temp.height=96;this.tctx=this.temp.getContext('2d',{willReadFrequently:true});}render({source,signal,time}){this.tctx.drawImage(source,0,0,128,96);const img=this.tctx.getImageData(0,0,128,96),d=img.data,threshold=150-signal.motion*110+Math.sin(time*.001)*12;for(let x=0;x<128;x++){let y=0;while(y<96){while(y<96&&this._lum(d,(y*128+x)*4)<threshold)y++;const start=y;while(y<96&&this._lum(d,(y*128+x)*4)>=threshold)y++;const end=y;if(end-start<3)continue;const seg=[];for(let yy=start;yy<end;yy++){const i=(yy*128+x)*4;seg.push([d[i],d[i+1],d[i+2],this._lum(d,i)]);}seg.sort((a,b)=>a[3]-b[3]);if((x+Math.floor(time*.006))%7<3)seg.reverse();for(let yy=start;yy<end;yy++){const i=(yy*128+x)*4,s=seg[yy-start];d[i]=s[0];d[i+1]=s[1];d[i+2]=s[2];}}}this.tctx.putImageData(img,0,0);this.ctx.imageSmoothingEnabled=false;this.ctx.drawImage(this.temp,0,0,this.canvas.width,this.canvas.height);} _lum(d,i){return d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722;}}
class SampledEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);this.sample=document.createElement('canvas');this.sample.width=96;this.sample.height=72;this.sctx=this.sample.getContext('2d',{willReadFrequently:true});this.maskSample=document.createElement('canvas');this.maskSample.width=96;this.maskSample.height=72;this.mctx=this.maskSample.getContext('2d',{willReadFrequently:true});}sampleFrame(source,mask){this.sctx.drawImage(source,0,0,96,72);this.mctx.drawImage(mask,0,0,96,72);return[this.sctx.getImageData(0,0,96,72).data,this.mctx.getImageData(0,0,96,72).data];}}
export class PoseDepthEffect extends SampledEffect{render({source,mask,landmarks,signal}){const c=this.ctx,w=this.canvas.width,h=this.canvas.height,[d,md]=this.sampleFrame(source,mask);c.fillStyle='#020408';c.fillRect(0,0,w,h);c.globalCompositeOperation='lighter';for(let y=1;y<72;y+=3)for(let x=1;x<96;x+=3){const i=(y*96+x)*4;if(md[i]<45&&signal.poseReady)continue;const lum=(d[i]*.21+d[i+1]*.72+d[i+2]*.07)/255,z=(lum-.5)*18,px=(x/96*w-w*.5)*(1+z*.006)+w*.5,py=(y/72*h-h*.5)*(1+z*.006)+h*.5,size=.8+lum*2.8;c.fillStyle=`rgba(${d[i]},${d[i+1]},${d[i+2]},${.18+lum*.75})`;c.fillRect(px-size/2,py-size/2,size,size);}const pose=landmarks?.[0];if(pose){c.strokeStyle='rgba(190,255,255,.6)';c.lineWidth=1;for(const[a,b]of POSE_CONNECTIONS){if(!pose[a]||!pose[b])continue;c.beginPath();c.moveTo(pose[a].x*w,pose[a].y*h);c.lineTo(pose[b].x*w,pose[b].y*h);c.stroke();}}c.globalCompositeOperation='source-over';}}
export class PoseMeshEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);}render({source,landmarks}){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.fillStyle='#08040e';c.fillRect(0,0,w,h);const pose=landmarks?.[0];if(pose?.length){c.globalCompositeOperation='lighter';const nodes=[];for(let i=0;i<pose.length;i++){const p=pose[i];if((p.visibility??1)<.35)continue;nodes.push({x:p.x*w,y:p.y*h,z:p.z||0,i});}for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<75){c.strokeStyle=`rgba(130,220,255,${(1-dist/75)*.22})`;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}}for(const n of nodes){c.fillStyle='rgba(235,255,255,.85)';c.fillRect(n.x-1.5,n.y-1.5,3,3);}c.globalCompositeOperation='source-over';}else{c.globalAlpha=.35;c.drawImage(source,0,0,w,h);c.globalAlpha=1;}}}
export class MaskBeadsEffect extends SampledEffect{constructor(canvas,dense=true){super(canvas);this.dense=dense;}render({source,mask,signal}){const[d,md]=this.sampleFrame(source,mask),c=this.ctx,w=this.canvas.width,h=this.canvas.height,step=this.dense?3:6;c.fillStyle='#06070b';c.fillRect(0,0,w,h);for(let y=step/2;y<72;y+=step)for(let x=step/2;x<96;x+=step){const i=((y|0)*96+(x|0))*4,lum=(d[i]*.21+d[i+1]*.72+d[i+2]*.07)/255,inside=md[i]/255;if(signal.poseReady&&inside<.12&&!this.dense)continue;const px=x/96*w,py=y/72*h,r=(step*.35+lum*step*.2)*(w/96);c.fillStyle=`rgba(0,0,0,${.25+lum*.25})`;c.beginPath();c.arc(px+r*.2,py+r*.35,r,0,TAU);c.fill();const g=c.createRadialGradient(px-r*.3,py-r*.3,r*.05,px,py,r);g.addColorStop(0,`rgb(${Math.min(255,d[i]+100)},${Math.min(255,d[i+1]+100)},${Math.min(255,d[i+2]+100)})`);g.addColorStop(.45,`rgb(${d[i]},${d[i+1]},${d[i+2]})`);g.addColorStop(1,`rgb(${d[i]*.4},${d[i+1]*.4},${d[i+2]*.4})`);c.fillStyle=g;c.beginPath();c.arc(px,py,r,0,TAU);c.fill();if(!this.dense){c.fillStyle='rgba(4,4,8,.75)';c.beginPath();c.arc(px,py,r*.3,0,TAU);c.fill();}}}}
export class FlowRingsEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);}render({source,signal,time}){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.globalAlpha=.2;c.drawImage(source,0,0,w,h);c.globalAlpha=1;c.globalCompositeOperation='lighter';const cx=signal.motionX*w,cy=signal.motionY*h,base=time*.08,max=Math.hypot(w,h)*.68;for(let i=0;i<28;i++){const r=(base+i*18)%max,a=Math.max(0,1-r/max)*(.08+signal.motion*.5);c.strokeStyle=`hsla(${185+i*7},100%,70%,${a})`;c.lineWidth=.6+(i%4)*.35;c.beginPath();c.ellipse(cx,cy,r,r*.72,Math.atan2(signal.flowY||0,signal.flowX||1)*.1,0,TAU);c.stroke();}c.globalCompositeOperation='source-over';}}
export class AsciiEffect{constructor(canvas){this.canvas=canvas;this.ctx=ctx2d(canvas);this.sample=document.createElement('canvas');this.sample.width=90;this.sample.height=60;this.sctx=this.sample.getContext('2d',{willReadFrequently:true});}render({source}){const chars=' .,:;irsXA253hMHGS#9B&@';this.sctx.drawImage(source,0,0,90,60);const d=this.sctx.getImageData(0,0,90,60).data,c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.fillStyle='#030508';c.fillRect(0,0,w,h);c.font='700 8px ui-monospace,monospace';c.textBaseline='top';const sx=w/45,sy=h/24;for(let row=0;row<24;row++)for(let col=0;col<45;col++){const x=Math.floor(col/45*90),y=Math.floor(row/24*60),i=(y*90+x)*4,lum=(d[i]*.21+d[i+1]*.72+d[i+2]*.07)/255,idx=Math.min(chars.length-1,Math.floor(Math.pow(lum,.7)*chars.length));if(idx<2)continue;c.fillStyle=`rgba(${Math.min(255,d[i]*1.3)},${Math.min(255,d[i+1]*1.3)},${Math.min(255,d[i+2]*1.3)},${.25+lum*.75})`;c.fillText(chars[idx],col*sx,row*sy);}}}
export const slitScanFactory=({canvas})=>new SlitScanEffect(canvas);
export const flowParticlesFactory=({canvas,analysis})=>new OpticalFlowParticlesEffect(canvas,analysis);
export const pixelSortFactory=({canvas})=>new PixelSortEffect(canvas);
export const poseDepthFactory=({canvas})=>new PoseDepthEffect(canvas);
export const poseMeshFactory=({canvas})=>new PoseMeshEffect(canvas);
export const hdBeadsFactory=({canvas})=>new MaskBeadsEffect(canvas,true);
export const beadsFactory=({canvas})=>new MaskBeadsEffect(canvas,false);
export const ringsFactory=({canvas})=>new FlowRingsEffect(canvas);
export const asciiFactory=({canvas})=>new AsciiEffect(canvas);
