import { GLPipeline } from '../gpu/shader-pass.js';
export class PipelineEffect{constructor(canvas,chain){this.canvas=canvas;this.chain=chain;this.pipeline=null;this.fallback=null;}init(){try{this.pipeline=new GLPipeline(this.canvas);}catch(error){console.warn('[gpu] falling back to 2D',error);this.fallback=this.canvas.getContext('2d');}}render({source,flow,mask,signal,time}){if(this.pipeline)this.pipeline.render({source,flow,mask,signal,time,chain:this.chain});else this.fallback?.drawImage(source,0,0,this.canvas.width,this.canvas.height);}dispose(){this.pipeline?.dispose();}}
const V=`#version 300 es
precision highp float;const vec2 P[3]=vec2[3](vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));out vec2 vUv;void main(){vec2 p=P[gl_VertexID];vUv=p*.5+.5;gl_Position=vec4(p,0,1);}`;
const STEP=`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uState;uniform sampler2D uSource;uniform sampler2D uMask;uniform vec2 uTexel;uniform float uMotion;uniform float uTime;vec2 s(vec2 o){return texture(uState,vUv+o*uTexel).rg;}void main(){vec2 c=s(vec2(0));vec2 lap=-c+.2*(s(vec2(1,0))+s(vec2(-1,0))+s(vec2(0,1))+s(vec2(0,-1)))+.05*(s(vec2(1,1))+s(vec2(-1,1))+s(vec2(1,-1))+s(vec2(-1,-1)));float a=c.r,b=c.g,feed=.0525+sin(uTime*.13)*.002,kill=.0615+cos(uTime*.11)*.0015,re=a*b*b;a+=lap.r-re+feed*(1.-a);b+=.52*lap.g+re-(kill+feed)*b;float lum=dot(texture(uSource,vUv).rgb,vec3(.2126,.7152,.0722));float edge=abs(lum-dot(texture(uSource,vUv+vec2(uTexel.x*2.,0)).rgb,vec3(.2126,.7152,.0722)))+abs(lum-dot(texture(uSource,vUv+vec2(0,uTexel.y*2.)).rgb,vec3(.2126,.7152,.0722)));float mask=texture(uMask,vUv).r;b+=edge*(.06+uMotion*.26)+smoothstep(.25,.85,mask)*uMotion*.009;a-=edge*uMotion*.03;outColor=vec4(clamp(a,0.,1.),clamp(b,0.,1.),0,1);}`;
const SHOW=`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uState;uniform sampler2D uSource;uniform sampler2D uMask;uniform float uTime;uniform float uMotion;void main(){vec2 ab=texture(uState,vUv).rg;float f=clamp(ab.g*2.4-ab.r*.5,0.,1.);vec3 src=texture(uSource,vUv).rgb;float mask=texture(uMask,vUv).r;vec3 pal=.5+.5*cos(vec3(.2,2.3,4.4)+f*5.5+uTime*.16);vec3 c=mix(src*.18,pal,f*.94);c+=pal*smoothstep(.15,.75,mask)*uMotion*.18;outColor=vec4(c,1);}`;
function sh(gl,t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(x));return x;}function prog(gl,f){const p=gl.createProgram();gl.attachShader(p,sh(gl,gl.VERTEX_SHADER,V));gl.attachShader(p,sh(gl,gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}function tex(gl,w,h,data=null,linear=false){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,data);return t;}
export class ReactionDiffusionEffect{constructor(canvas){this.canvas=canvas;this.gl=null;this.ctx2d=null;this.ready=false;}init(){try{const gl=this.canvas.getContext('webgl2',{antialias:false});this.gl=gl;if(!gl)throw new Error('WebGL2 unavailable');this.stepProgram=prog(gl,STEP);this.showProgram=prog(gl,SHOW);this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);this.fbo=gl.createFramebuffer();this.w=Math.min(192,this.canvas.width);this.h=Math.min(128,this.canvas.height);const init=new Uint8Array(this.w*this.h*4);for(let y=0;y<this.h;y++)for(let x=0;x<this.w;x++){const i=(y*this.w+x)*4;init[i]=255;init[i+3]=255;const cx=x-this.w*.5,cy=y-this.h*.5;if(cx*cx+cy*cy<90||((x*17+y*31)%997)<4){init[i]=80;init[i+1]=210;}}this.a=tex(gl,this.w,this.h,init);this.b=tex(gl,this.w,this.h,init);this.sourceTex=tex(gl,2,2,null,true);this.maskTex=tex(gl,2,2,null,true);this.ready=true;}catch(error){console.warn('[reaction] fallback',error);this.ctx2d=this.canvas.getContext('2d');}}_upload(t,c){const g=this.gl;g.bindTexture(g.TEXTURE_2D,t);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,c);}_bind(p,n,t,u){const g=this.gl,l=g.getUniformLocation(p,n);if(l===null)return;g.activeTexture(g.TEXTURE0+u);g.bindTexture(g.TEXTURE_2D,t);g.uniform1i(l,u);}render({source,mask,signal,time}){if(!this.ready){this.ctx2d?.drawImage(source,0,0,this.canvas.width,this.canvas.height);return;}const g=this.gl;this._upload(this.sourceTex,source);this._upload(this.maskTex,mask);const it=signal.motion>.12?6:4;for(let n=0;n<it;n++){g.bindFramebuffer(g.FRAMEBUFFER,this.fbo);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.b,0);g.viewport(0,0,this.w,this.h);g.useProgram(this.stepProgram);this._bind(this.stepProgram,'uState',this.a,0);this._bind(this.stepProgram,'uSource',this.sourceTex,1);this._bind(this.stepProgram,'uMask',this.maskTex,2);g.uniform2f(g.getUniformLocation(this.stepProgram,'uTexel'),1/this.w,1/this.h);g.uniform1f(g.getUniformLocation(this.stepProgram,'uMotion'),signal.motion||0);g.uniform1f(g.getUniformLocation(this.stepProgram,'uTime'),time*.001);g.drawArrays(g.TRIANGLES,0,3);[this.a,this.b]=[this.b,this.a];}g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.useProgram(this.showProgram);this._bind(this.showProgram,'uState',this.a,0);this._bind(this.showProgram,'uSource',this.sourceTex,1);this._bind(this.showProgram,'uMask',this.maskTex,2);g.uniform1f(g.getUniformLocation(this.showProgram,'uMotion'),signal.motion||0);g.uniform1f(g.getUniformLocation(this.showProgram,'uTime'),time*.001);g.drawArrays(g.TRIANGLES,0,3);}dispose(){if(!this.gl)return;for(const p of[this.stepProgram,this.showProgram])this.gl.deleteProgram(p);for(const t of[this.a,this.b,this.sourceTex,this.maskTex])this.gl.deleteTexture(t);this.gl.deleteFramebuffer(this.fbo);this.gl.deleteVertexArray(this.vao);}}
export const feedbackFactory=({canvas})=>new PipelineEffect(canvas,['feedback','chromatic']);
export const displacementFactory=({canvas})=>new PipelineEffect(canvas,['flowWarp','chromatic']);
export const reactionFactory=({canvas})=>new ReactionDiffusionEffect(canvas);
